"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](#bd93f9)\
$os\
$username\
[](bg:#ff79c6 fg:#bd93f9)\
$directory\
[](fg:#ff79c6 bg:#ffb86c)\
$git_branch\
$git_status\
[](fg:#ffb86c bg:#8be9fd)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#8be9fd bg:#6272a4)\
$docker_context\
$conda\
[](fg:#6272a4 bg:#33658A)\
$time\
[ ](fg:#33658A)\
$line_break$character"""


[os]
disabled = false
style = "bg:#bd93f9"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "bg:#bd93f9"
style_root = "bg:#bd93f9"
format = '[ $user ]($style)'
disabled = false

[directory]
style = "bg:#ff79c6"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[c]
symbol = " "
style = "bg:#8be9fd"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#6272a4"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:#8be9fd"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#8be9fd"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#ffb86c"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#ffb86c"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#8be9fd"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#8be9fd"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#8be9fd"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#8be9fd"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#8be9fd"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#8be9fd"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#8be9fd"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#8be9fd"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#8be9fd"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[  $time ]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
